networks:
  net1:






services:


  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: aio
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: qwe

    ports:
      - 5433:5432
    networks:
      net1:
        aliases:
          - database
